### ISSUE TITLE
dqn parameter sharing example

### ISSUE THREAD

**Issue by tahirbb** [marl-book/codebase#25]
According to the parameter sharing example

```console
python run.py +algorithm=dqn env.name="lbforaging:Foraging-8x8-4p-3f-v2" env.time_limit=25 algorithm.model.critic.parameter_sharing=True
```

generates error. It looks like dqn.yaml config is not include actor critic.

I successfully ran the example with command

```console
python run.py +algorithm=dqn env.name="lbforaging:Foraging-8x8-4p-3f-v2" env.time_limit=25 algorithm.model.parameter_sharing=True
```

**Comment by LukasSchaefer** [comment]
Hi, thanks for raising the issue!
We have resolved this error in the documentation with the recent PR :)
